# Generated by Django 2.0.4 on 2018-04-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='act',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='check_whether_is_working',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='outside_osmotr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='results_diag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='serial_n',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_device',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='working_was_done',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='responsive_person',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('d', 'Done'), ('p', 'Processing')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
